version: "3"

services:
  redis:
    image: redis
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=KaikkiOnHeikunKeikun
      - POSTGRES_USER=kontti
  backend:
    image: back:12
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=kontti
      - DB_PASSWORD=KaikkiOnHeikunKeikun
      - DB_HOST=database
    restart: unless-stopped
  frontend:
    image: front:12
    environment:
      - API_URL=/api/
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 800:800
