version: "3"

services:
  frontend:
    image: front
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  backend:
    image: back
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/backend/logs.txt
    environment:
      - REDIS=redis
